### ISSUE TITLE
Ho to use Linux version? 

### ISSUE THREAD

**Issue by Kryvytsky** [Anuken/animdustry#10]
Compared to the version of Windows and Android, there is no filename type in the end. How should I run it? 
![Screenshot_20220406_073306](https://user-images.githubusercontent.com/81460407/161897146-4eb9d702-356d-42c0-bfc5-1528530f9b63.jpg)

**Comment by Anuken** [comment]
Linux executables don't have extensions, you just run them. `chmod +x linux64` `./linux64`
