### ISSUE TITLE
Hardware input problem with Android version

### ISSUE THREAD

**Issue by PTALTS-LK** [Anuken/animdustry#14]
On Android version, OTG keyboard does not work (keyboard input does not respond to games)

**Comment by Anuken** [comment]
I wouldn't call this a bug - keyboard support was never implemented, you're expected to use swipe controls.

**Comment by PTALTS-LK** [comment]
> I wouldn't call this a bug - keyboard support was never implemented, you're expected to use swipe controls.

I think it's too hard to use）
😐

**Comment by nekonya3031** [comment]
maybe later add to screen buttons for mobile devices as option?

**Comment by Anuken** [comment]
Added support for arrow keys in 1.1.

**Comment by PTALTS-LK** [comment]
> Added support for arrow keys in 1.1.

OHHHHHHHHHHHHHHHHHHH
