### ISSUE TITLE
Build failed on Linux

### ISSUE THREAD

**Issue by PTALTS-LK** [Anuken/animdustry#17]
I try to compile on linux but I get the following terminal output
[logout.txt](https://github.com/Anuken/animdustry/files/8458076/logout.txt)

> /root/animdustry/fau/src/core.nim(162, 26) template/generic instantiation of `loadAtlas` from here                                                                              /root/animdustry/fau/src/fau/atlas.nim(16, 31) template/generic instantiation of `loadTexture` from here                                                                        /root/animdustry/fau/src/fau/texture.nim(134, 37) template/generic instantiation of `assetReadStatic` from here                                                                 /root/animdustry/fau/src/fau/assets.nim(66, 25) Error: cannot open file: /root/animdustry/assets/atlas.png

**Comment by Anuken** [comment]
Run `nimble pack`

**Comment by PCX-LK** [comment]
> Run `nimble pack`

Oh no

`❯ nimble pack                                                                             Executing task pack in /root/animdustry/animdustry.nimble                             sh: 1: faupack: not found                                                                    Error: Exception raised during nimble script execution`

**Comment by PCX-LK** [comment]
> Run `nimble pack`

Oh no

> ❯ nimble pack                                                                             Executing task pack in /root/animdustry/animdustry.nimble                             sh: 1: faupack: not found                                                                    Error: Exception raised during nimble script execution

**Comment by PTALTS-LK** [comment]
> Run `nimble pack`

Oh no 

> ❯nimble pack
Executing task pack in /root/animdustry/animdustry.nimble
sh: 1: faupack: not found
Error: Exception raised during nimble script execution

**Comment by Anuken** [comment]
You likely failed to follow the Nim installation instructions  - `.nimble/bin` is not on your path.
