### ISSUE TITLE
Gameplay bug

### ISSUE THREAD

**Issue by Slawmee** [Anuken/animdustry#20]
You can spam click the play button or just use autoclicker to play the game even when you already lost

![Screenshot_20220420-141255](https://user-images.githubusercontent.com/83009426/164163748-fa4c6dd5-557e-485b-b3db-fd7c7d9b48fb.jpg)
![Screenshot_20220420-141308](https://user-images.githubusercontent.com/83009426/164163810-1f839dd9-3ecb-4551-93f5-ead4f5efac23.jpg)

**Comment by Anuken** [comment]
Fixed.
