### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Slawmee** [Anuken/animdustry#21]
You can spam click the play button when you win and it will give you the same ammount of copper

![Screenshot_20220421-142213](https://user-images.githubusercontent.com/83009426/164388115-0684dcce-36b5-49cc-adcc-73683e8be4bc.jpg)
![Screenshot_20220421-142511](https://user-images.githubusercontent.com/83009426/164388140-28c74f13-6169-472b-9c30-3ea6ee610d29.jpg)
![Screenshot_20220421-142517](https://user-images.githubusercontent.com/83009426/164388170-824d48a7-1eb2-41a4-b393-cff5c3f66026.jpg)

**Comment by Delourians** [comment]
Hmmm looks like Im not gonna update my game

**Comment by Delourians** [comment]
XD HAHAHAHAHAHAHA




![Screenshot_20220421-144304.jpg](https://user-images.githubusercontent.com/84485006/164391038-c818c1db-5dc9-4394-bb87-c1af176c512d.jpg)

**Comment by Anuken** [comment]
Already fixed.
