### ISSUE TITLE
Bug Report: Missing Alpha-chan eyes (Minor bug)

### ISSUE THREAD

**Issue by TheMrAlbert** [Anuken/animdustry#23]
**Platform**: Windows 10

**Version**: 1.1

**Issue**: Alpha-chan eyes gone missing when minimizing on settings screen. This bug reproduction is different from #19.

**Steps to reproduce**: On settings screen, minimize the window and restore it back.

**Save file**: Not included

**(Crash) logs**: None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/anindustry) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

https://user-images.githubusercontent.com/44728043/165201590-1ea6143a-1353-48c5-b204-cb81e921f2bf.mp4

**Comment by Anuken** [comment]
This does not happen to me on Linux.

**Comment by Anuken** [comment]
Tested with Wine now, and it looks like, for some god-forsaken reason, Windows sets the window size to 0 when minizing. Brilliant.
