### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by ZhangBai-Zero** [Anuken/animdustry#25]
When I click the event in Mindustry, an error dialog box will pop up. I don't know why. 
This problem also occurs when I download the EXE file directly from GitHub and open it.
![b5137ee460757ca53d347b41f597d9c](https://user-images.githubusercontent.com/104487647/166094259-fd643385-506c-47a6-bc31-090be55a268d.png)

**Comment by Anuken** [comment]
I've fixed the crash itself, but the real issue here is that the game can't write to the directory you've censored out there. I don't know why that is - figure out why the directory isn't writeable, or try running the game as an admin.
