### ISSUE TITLE
You should probably add mercurial to dependencies

### ISSUE THREAD

**Issue by PTALTS-LK** [Anuken/animdustry#26]
Not every linux/mac os computer has this package

**Comment by Anuken** [comment]
Where is mercurial used in this repository...?

**Comment by PTALTS-LK** [comment]
> Where is mercurial used in this repository...?

When I tried to build before, the terminal reported that the command 'hg' was not found, the 'hg' command is provided by the mercurial package

**Comment by PTALTS-LK** [comment]
> Where is mercurial used in this repository...?

![Screenshot_20220501210938](https://user-images.githubusercontent.com/62936489/166147430-3caebc3f-c8fc-48f0-9ec7-fe7ff4364b2d.jpg)

**Comment by PTALTS-LK** [comment]
> Where is mercurial used in this repository...?

And also had this problem on my friend's Mac OS

**Comment by Anuken** [comment]
I've never seen anyone with that problem before. fau is a *git* repository, that URL doesn't make any sense and cloning a git repository with hg wouldn't work anyway.

**Comment by PTALTS-LK** [comment]
> I've never seen anyone with that problem before. fau is a _git_ repository, that URL doesn't make any sense and cloning a git repository with hg wouldn't work anyway.

So what do you think the problem is?

**Comment by Anuken** [comment]
No idea.

**Comment by PTALTS-LK** [comment]
> No idea.

The strange thing is that when I just removed mercurial and then executed nimble install -y -d again, there was no error in the terminal

Here is the result running on my friend's Mac OS
![-7a369194c5cb38ef](https://user-images.githubusercontent.com/62936489/166148997-a2877fe8-ea90-45f8-84bd-5589b963bfaa.jpg)

**Comment by PTALTS-LK** [comment]
And this problem also occurs on my friend's newly installed Debian
![4bb594feac12089c](https://user-images.githubusercontent.com/62936489/166224958-399abcc9-f78c-418e-ad48-bf1e6ca4604f.jpg)
