### ISSUE TITLE
“Needs authorization” (Google chrome)

### ISSUE THREAD

**Issue by dekiitteh** [Anuken/animdustry#30]
It says “To fix the error, contact the website or server owner, or try to find the file on a different site.” so help me plz

**Comment by dekiitteh** [comment]
Same error with Mindustry-BE-Desktop-23162.jar so can you fix?

**Comment by Anuken** [comment]
what on earth is this

**Comment by dekiitteh** [comment]
![lag](https://user-images.githubusercontent.com/110713540/190160133-0e8a9c21-728f-4283-8318-890bba2c1ecf.png)
 help

**Comment by Anuken** [comment]
That has nothing to do with me, I cannot help you. Something is blocking it on your end.
