### ISSUE TITLE
what is the image licence?

### ISSUE THREAD

**Issue by dekiitteh** [Anuken/animdustry#31]
i created an empty unofficial fandom wiki but i need the images

**Comment by nicodium** [comment]
[animdustry](https://github.com/Anuken/animdustry/tree/v1.2)/[assets](https://github.com/Anuken/animdustry/tree/v1.2/assets)/textures/

**Comment by Anuken** [comment]
I don't know, what are such images usually licensed as? I'd probably use some CC attribution license for those.

**Comment by nicodium** [comment]
Normally CC-BY-SA. You can consult https://creativecommons.org/licenses/ for more info

**Comment by dekiitteh** [comment]
> I don't know, what are such images usually licensed as? I'd probably use some CC attribution license for those.

ok cool :D
