### ISSUE TITLE
Fau breaks when compiling in WSL

### ISSUE THREAD

**Issue by SantiGameDev** [Anuken/animdustry#32]
Fau doesn't seem to have an issues page, so I had to put it here.

I was just going to do an unmodded build to make sure my environment was configured and this popped up.

```
/mnt/c/Users/----/repos/animdustry/fau/src/fau/g2/font.nim(77, 16) template/generic instantiation of `[]=` from here
/home/----/.nimble/pkgs/pixie-5.0.6/pixie/images.nim(45, 24) template/generic instantiation of `[]=` from here
/home/----/.nimble/pkgs/pixie-5 .0. 6/pixie/images.nim(35, 43) Error: attempting to call undeclared routine: 'datalndex'
Error: Exception raised during nimble script execution
```

**Comment by Anuken** [comment]
> Error: attempting to call undeclared routine: 'datalndex'

This looks like a typo in a package (L instead of I?), except it's not my package, a typo doesn't make sense at all, and frankly I'm not maintaining anything in this repo anymore, so you'll have to figure out the problem yourself, because I've never seen it before.

**Comment by SantiGameDev** [comment]
Well, guess I'm porting this

**Comment by SantiGameDev** [comment]
Hold on, so you made a game engine, specifically for a game, specifically for an April Fool's joke? I've been working on my own engine for THREE YEARS!

![anakin-skywalker-palpatine.gif](https://user-images.githubusercontent.com/93549981/229602437-669bb377-2015-4b93-b046-7d0b02db4331.gif)
