### ISSUE TITLE
what art style is the splash image of animdustry

### ISSUE THREAD

**Issue by ghost** [Anuken/animdustry#36]
what is the art style of these splash images 
![alpha](https://github.com/Anuken/animdustry/assets/99548235/b91ee272-71cf-4f85-874a-8026d19ec92f)
![crawler](https://github.com/Anuken/animdustry/assets/99548235/3aa4f4bd-df05-4668-a03f-5aa5fa7d3c4f)

**Comment by Anuken** [comment]
I don't know, probably just "cel shaded"? Line-less? It's not based on any existing artist's style in particular.

**Comment by ghost** [comment]
also did you use a color palette ?

**Comment by Anuken** [comment]
Yes. It's pixel art with antialising and a black outline applied afterwards.

**Comment by ghost** [comment]
is that for the pixel art or the flash art

**Comment by Anuken** [comment]
The art you posted.

**Comment by ghost** [comment]
I don't understand , is the name of the color palette ' pixel art with antialiasing and a black outline' ?

**Comment by Anuken** [comment]
The color palette doesn't have a name, I picked out the colors myself.

**Comment by ghost** [comment]
ok , thanks for the help























btw i ship crawler with nale (renale)
cute

**Comment by ghost** [comment]
wrong chat
any ways i am gonna pound sand
     
     
 
 
 
 
 
 
  
  
 
 
 
 
 
 
 
 
 
 and never gonna give you up
