### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by Hu1night** [Anuken/animdustry#5]

**Comment by PTALTS-LK** [comment]
同志，这么个小游戏要啥汉化啊

**Comment by xem8k5** [comment]
我寻思初中英语都看得懂。。。。

**Comment by WilloIzCitron** [comment]
![image](https://user-images.githubusercontent.com/49786146/162640990-b850c016-756f-4d61-8352-42d9a60be507.png)
Translated: 完全超出范围，字体现在根本不支持 CJK，也无法加载文本包
