### ISSUE TITLE
FAU engine does not respect DPI scaling

### ISSUE THREAD

**Issue by Dat-Guy** [Anuken/animdustry#7]
The mouse's effective position in the window appears to be at half scale to it's actual position, i.e. when the cursor is at the bottom-right corner, the game registers it as being in the center.

Looking into the code, this appears to be an issue with the engine itself using logical pixels (mouse position) against physical pixels (rendering), as the screen's dimensions are used for rendering and it appears fine.

**Comment by Anuken** [comment]
This may be fixed in the latest version, try re-compiling. I don't have a machine that supports this.
